

server:
  port: 8849

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feed
    username: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 1000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
